<?php

/**
 * @file
 * Contains js_3rd_party.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function js_3rd_party_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the js_3rd_party module.
        case 'help.page.js_3rd_party':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('La forma correcta de importar librerias') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function js_3rd_party_theme() {
    return [
        'js_3rd_party' => [
            'variables' => [],
        ],
    ];
}













